//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12
#![allow(unused_imports)]

pub use super::authors::Entity as Authors;
pub use super::books::Entity as Books;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::roles::Entity as Roles;
pub use super::users::Entity as Users;
pub use super::users_roles::Entity as UsersRoles;
